import '../../globals.css';
export const metadata = {
	title: 'Create Login',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <section className=''>{children}</section>;
}
